### ISSUE TITLE
python install SyntaxError

### ISSUE THREAD

**Issue by rrgupta** [thespacedoctor/panstamps#1]
Hi,

I am trying to install panstamps via git as per the README instructions:
```
git clone git@github.com:thespacedoctor/panstamps.git
cd panstamps
python setup.py install
```
but am getting the following error (when attempting to install on both my Mac OSX laptop and my linux machine):
```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    exec(open(moduleDirectory + "/panstamps/__version__.py").read())
  File "<string>", line 1
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
```
It doesn't seem like this error is related to necessary pillow external libraries, but perhaps it is. 

I also tried to install via pip but got stuck after `Collecting MySQL-python (from fundamentals->panstamps)`. I ran into 
```
EnvironmentError: mysql_config not found
```
Any idea how to fix or get around these errors?
Thanks,
Ravi

**Comment by thespacedoctor** [comment]
Hi Ravi,

Sorry there was a conflict in the __version__.py file that I obviously hadn't resolved before pushing to github.

I've solved that issue, and I've also removed the MySQL-python dependency from my [fundamentals](https://github.com/thespacedoctor/fundamentals) package so that users without mysql installed on their machines can still install panstamps.

Please try again now with `pip install panstamps`.
